SECRET_KEY = 'super-secret'
SQLALCHEMY_DATABASE_URI = 'sqlite:///data.db'
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = True
SECURITY_PASSWORD_HASH = 'sha512_crypt'
SECURITY_PASSWORD_SALT = 'соль = несколько случайных слов'
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_TRACKABLE = True

MAIL_SERVER = 'smtp.mail.ru'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = 'SECRET'
MAIL_PASSWORD = 'SECRET'

BABEL_DEFAULT_LOCALE = 'ru_RU'
